name: BC Lint

on:
  # Copied from check-labels.yml to get around needing approval for first time contributors
  # We need pull_request_target to be able to post comments on PRs from forks.
  # See https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
  # Only allow pull_request_target when merging to main, not some historical branch.
  #
  # Make sure to don't introduce explicit checking out and installing/running
  # untrusted user code into this workflow!
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [main]
    paths-ignore: [.github/workflows/lint-bc.yaml]

  # To allow testing PRs that change workflows.
  # May be triggered together with pull_request_target, it's OK.
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths: [.github/workflows/lint-bc.yaml]
    branches-ignore: [nightly]

  workflow_dispatch:

jobs:
  bc_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Run BC Lint Action
        uses: pytorch/test-infra/.github/actions/bc-lint@main
        with:
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          suppression: ${{ contains(github.event.pull_request.labels.*.name, 'suppress-api-compatibility-check') || contains(github.event.pull_request.labels.*.name, 'suppress-bc-linter') }}
          docs_link: 'https://github.com/pytorch/test-infra/wiki/BC-Linter'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
